baseURL = 'https://example.org/'
languageCode = 'de-DE'
efaultContentLanguage = 'de-DE'
title = 'The Blog of DO3EET'

theme = "risotto"
paginate = 3
enableInlineShortcodes = true
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

[params.about]
title = "DO3EET"
description = "Ich bin Frank. Ein Informatiker und Funkamateur aus Deutschland. Außerdem reise ich gern nach Japan."

[markup.goldmark.renderer]
unsafe = true

