baseURL = 'https://example.org/'
languageCode = 'de-DE'
efaultContentLanguage = 'de-DE'
title = 'The Blog of DO3EET'

theme = "risotto"
paginate = 3
enableInlineShortcodes = true
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

[params.about]
title = "DO3EET"
description = "Ich bin Frank. Ein Informatiker und Funkamateur aus Deutschland. Außerdem reise ich gern nach Japan."

[markup.goldmark.renderer]
unsafe = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:planung@dreamofjapan.de?subject=DO3EET%20Blog%3A%20%3CYour%20Topic%3E"