baseURL = 'https://do3eet.pages.dev'
languageCode = 'de-DE'
defaultContentLanguage = 'de'
enableMissingTranslationPlaceholders = true
title = 'The Blog of DO3EET'
theme = ["hugo-video", "risotto"]
pagination.pagerSize = 3
enableInlineShortcodes = true
[menu]
[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 20
[[menu.main]]
  name = "tags"
  url = "/tags/"
  weight = 30

[params]
noindex = false
defaultFallbackLanguage = "de"

[params.theme]
palette = "tokyo-night-dark"

[params.about]
title = "DO3EET"
description = "Ich bin Frank. Ein Informatiker und Funkamateur aus Deutschland. Außerdem reise ich gern nach Japan."

[params.author]
name = 'DO3EET'


[markup.goldmark.renderer]
unsafe = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.x]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true



[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:planung@dreamofjapan.de?subject=DO3EET%20Blog%3A%20%3CYour%20Topic%3E"

[[params.socialLinks]]
icon = "fa-solid fa-comment-dots"
title = "Matrix Chat"
url = "https://matrix.to/#/@bollerwagenpicard:tchncs.de"

[[params.socialLinks]]
icon = "fa-solid fa-rss"
title = "RSS"
url = "https://do3eet.pages.dev/index.xml"

[params.giscus]
repo = "frankenstein91/DO3EET-webseite"
repoID = "R_kgDOKsmxqw"
category = "Announcements"
categoryID = "DIC_kwDOKsmxq84Ca5h5"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "1"
inputPosition = "top"
theme = "dark_protanopia"
lang = "de"
loading = "lazy"

[module]

[[module.imports]]

    path = 'github.com/hugomods/images'

[outputs]
section = ['html', 'rss', 'amp']
page = ['html', 'rss', 'amp']

[Author]
name = "Frank Tornack"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 10

  [languages.en]
    languageName = "English"
    weight = 20